bireme/accounts/urls.py
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

# enable django admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    re_path(r'^', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.urls')),
    path('api/', include('api.urls')),

    # internationalization
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^cookie-lang/', include('utils.urls')),
]


# messages translation
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

bireme/api/urls.py
from django.urls import path, re_path, include
from api.api import UserResource

from api import views as api_views

user_resource = UserResource()

app_name = 'api'

urlpatterns = [
    re_path(r'^auth/', include(user_resource.urls)),
    re_path(r'^users/edit/change-user-role-service/?$', api_views.change_user_role_service, name='change_user_role_service'),
    re_path(r'^networks/edit/change-network-member/?$', api_views.change_network_member, name='change_network_member'),
    re_path(r'^get_ccs/?$', api_views.get_ccs, name='get_ccs'),
    re_path(r'^get_network_ccs/?$', api_views.get_network_ccs, name='get_network_ccs')
]

bireme/main/urls.py
from django.urls import path, re_path

from main import views as main_views

app_name = 'main'

urlpatterns = [

    re_path(r'^$', main_views.dashboard, name='dashboard'),

    re_path(r'^users/?$', main_views.users, name='users'),
    re_path(r'^users/new/?$', main_views.new_user, name='new_user'),
    re_path(r'^users/edit/(?P<user>\d+)/?$', main_views.edit_user, name='edit_user'),

    re_path(r'^networks/?$', main_views.networks, name='networks'),
    re_path(r'^network/new/?$', main_views.new_network, name='new_network'),
    re_path(r'^network/edit/(?P<network>\d+)/?$', main_views.edit_network, name='edit_network'),

    re_path(r'^services/?$', main_views.services, name='services'),
    re_path(r'^services/new/?$', main_views.new_service, name='new_service'),
    re_path(r'^services/edit/(?P<service>\d+)/?$', main_views.edit_service, name='edit_service'),

    re_path(r'^roles/?$', main_views.roles, name='roles'),
    re_path(r'^roles/new/?$', main_views.new_role, name='new_role'),
    re_path(r'^roles/edit/(?P<role>\d+)/?$', main_views.edit_role, name='edit_role'),

]

bireme/utils/urls.py
from django.urls import path, re_path

from utils import views as utils_views

app_name = 'utils'

urlpatterns = [
    re_path(r'^$', utils_views.cookie_lang, name='cookie_lang'),
]

bireme/templates/alert.html
{% if alert %}
<script>
    $(function(){
        $('.alert').alert();
        setTimeout(function() {
            $('.box-alerts').fadeOut('slow');
        }, 5000);  
    });
</script>

<div class='box-alerts'>
    <div class="alert {{ alerttype }}">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      {{ alert }}
    </div>
</div>
{% endif %}

bireme/templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Bootstrap/CSS files -->
        <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "bootstrap/css/bootstrap-responsive.css" %}" rel="stylesheet">
        <link href="{% static "fort-awesome/css/font-awesome.css" %}" rel="stylesheet">
        <link href="{% static "css/screen.css" %}" rel="stylesheet">

        <title>{% block title %}{% trans "BIREME Accounts" %}{% endblock %}</title>

        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
        {% block extrahead %}{% endblock %}
    </head>

    <body>
        <div class='mask'><img src='{% static "image/loading.gif" %}'></div>
        <div class="wrap">



            {% block "body" %}
                {% block top %}{% include 'menu.html' %}{% endblock %}

                <ul class="breadcrumb">
                    <li><a href="{% url 'main:dashboard' %}">Home</a> <span class="divider">/</span></li>
                    {% block breadcrumb %}{% endblock %}
                </ul>


                <div class="container-fluid content main">
                    {% block content %}{% endblock %}
                </div>
            {% endblock %}

            {% block footer %}
            <div class='content' id="footer">
                    <p>
                        <img src="{% static "image/logo-BIREME.png" %}" title="BIREME/OPAS/OMS" />

                        <b class="bireme">{% trans "BIREME - PAHO - WHO" %}</b><br>
                        {% trans "Latin-American and Caribbean Center on Health Sciences Information" %}<br>
                        <a href="http://www.paho.org/bireme/" title="{% trans 'BIREME site' %}" target="_blank">http://www.paho.org/bireme/</a><br>
                        <small>v{% include 'version.txt' %} | <a target="_blank" href="http://github.com/bireme/accounts" title="{% trans "Project source on GitHub" %}">{% trans "code on github" %}</a></small>
                    </p>
            </div>
            {% endblock %}

        </div>

        <!-- javascript files -->

        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-dropdown.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-modal.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-transition.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-alert.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-tab.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap-typeahead.js" %}"></script>
        <script src="{% static "js/actions.js" %}"></script>
        <script>
            $(function(){
                $(".errorlist").addClass('alert alert-error');
            });
        </script>

        {% include "lang.html" %}
        {% include "alert.html" %}

        {% block extrajs %}{% endblock %}

    </body>
</html>

bireme/templates/lang.html
<script>
// change language
function change_language(lang) {
    // chama, via ajax, a view que armazena a linguagem em cookie, para relembrar na proxima entrada
    $.get("{% url 'utils:cookie_lang' %}", { language: lang} , function(data) {
        var form = document.language;
        form.language.value = lang;
        form.submit();
    });
}
</script>

<form action="{% url 'set_language' %}" method="post" id="setlang" name="language">
	{% csrf_token %}
	<input name="next" type="hidden" value="{{ redirect_to }}" />
	<input name="language" type="hidden" value="{{ LANGUAGE_CODE }}"  id="lang"/>
</form>

bireme/templates/menu.html
{% load i18n %}
{% block menu %}
    {% if user.is_authenticated %}

        <div class="navbar navbar-fixed-top" id="menu">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <div class="row-fluid top">

                        <ul class="nav pull-left">
                            <li><a href="{% url 'main:dashboard' %}" title="{% trans "Dashboard" %}"><i class="icon-home"></i> {% trans "Dashboard" %}</a></li>

                            {% if user.profile.type == "advanced" or user.is_superuser %}
                                <li><a href="{% url 'main:users' %}" title="{% trans "Users" %}"><i class="icon-group"></i> {% trans "Users" %}</a></li>
                                <li><a href="{% url 'main:networks' %}" title=""><i class="icon-sitemap"></i> {% trans "Networks" %}</a></li>
                            {% endif %}

                            {% if user.is_superuser %}
                                <li><a href="{% url 'main:services' %}" title=""><i class="icon-star"></i> {% trans "Services" %}</a></li>
                                <li><a href="{% url 'main:roles' %}" title=""><i class="icon-lock"></i> {% trans "Roles" %}</a></li>
                                <li><a href="{% url 'admin:index' %}" title=""><i class="icon-lock"></i> {% trans "Django Admin" %}</a></li>
                            {% endif %}
                        </ul>

                        <ul class="nav pull-right">
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="menu_language">
                                    <i class="icon-flag"></i>
                                    {% if LANGUAGE_CODE == 'en' %}{% trans "English"|capfirst %}{% endif %}
                                    {% if LANGUAGE_CODE == 'es' %}{% trans "Spanish"|capfirst %}{% endif %}
                                    {% if LANGUAGE_CODE == 'pt-br' %}{% trans "Portuguese"|capfirst %}{% endif %}
                                    <i class="icon-caret-down"></i>
                                </a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="menu_language">
                                    {% if LANGUAGE_CODE != "en" %}<li><a href="javascript: change_language('en')" title="{% trans 'English' %}">{% trans 'English'|capfirst %}</a></li>{% endif %}
                                    {% if LANGUAGE_CODE != "pt-br" %}<li><a href="javascript: change_language('pt-BR')" title="{% trans 'Portuguese' %}">{% trans 'Portuguese'|capfirst %}</a></li>{% endif %}
                                    {% if LANGUAGE_CODE != "es" %}<li><a href="javascript: change_language('es')" title="{% trans 'Spanish' %}">{% trans 'Spanish'|capfirst %}</a></li>{% endif %}
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="menu_profile">
                                    <i class="icon-user"></i><i class="icon-caret-down"></i>
                                </a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="menu_profile">
                                    <li><a href="{% url 'change_profile' %}" title="{% trans "Edit profile" %}">{% trans "Edit profile" %}</a></li>
                                    <li><a href="{% url 'auth_password_change' %}" title="{% trans "Change Password" %}">{% trans "Change password" %}</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'auth_logout' %}" title="Logout"><i class="icon-signout"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}