app/accounts/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

# enable django admin:
admin.autodiscover()

urlpatterns = [
    # Main app URLs at root
    path('', include('main.urls')),

    # Admin interface
    path('admin/', admin.site.urls),

    # Registration/authentication URLs
    path('accounts/', include('registration.urls')),

    # Internationalization and utils URLs
    path('i18n/', include('django.conf.urls.i18n')),
    path('cookie-lang/', include('utils.urls')),

    # API URLs
    path('api/', include('api.urls')),

]

# TODO: Add rosetta URLs when rosetta app is properly configured
# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
#     ]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

app/api/urls.py
from django.urls import path, re_path, include
from api.api import UserResource
from api import views as api_views

user_resource = UserResource()

app_name = 'api'

urlpatterns = [
    # Tastypie UserResource URLs (uses internal routing)
    re_path(r'^auth/', include(user_resource.urls)),

    # User role service management
    path('users/edit/change-user-role-service/', api_views.change_user_role_service, name='change_user_role_service'),

    # Network member management
    path('networks/edit/change-network-member/', api_views.change_network_member, name='change_network_member'),

    # Cooperative center APIs
    path('get_ccs/', api_views.get_ccs, name='get_ccs'),
    path('get_network_ccs/', api_views.get_network_ccs, name='get_network_ccs'),
]

app/main/urls.py
from django.urls import path, re_path

from main import views as main_views

app_name = 'main'

urlpatterns = [
    # Dashboard - can use path() since it's just root
    path('', main_views.dashboard, name='dashboard'),

    # Users URLs
    path('users/', main_views.users, name='users'),
    path('users/new/', main_views.new_user, name='new_user'),
    path('users/edit/<int:user>/', main_views.edit_user, name='edit_user'),

    # Networks URLs
    path('networks/', main_views.networks, name='networks'),
    path('network/new/', main_views.new_network, name='new_network'),
    path('network/edit/<int:network>/', main_views.edit_network, name='edit_network'),

    # Services URLs
    path('services/', main_views.services, name='services'),
    path('services/new/', main_views.new_service, name='new_service'),
    path('services/edit/<int:service>/', main_views.edit_service, name='edit_service'),

    # Roles URLs
    path('roles/', main_views.roles, name='roles'),
    path('roles/new/', main_views.new_role, name='new_role'),
    path('roles/edit/<int:role>/', main_views.edit_role, name='edit_role'),
]

app/main/models.py
# coding: utf-8
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from datetime import datetime
from django.db import models
from django.db.models.signals import post_save

from utils.models import Generic, Country, LANGUAGES_CHOICES

class Profile(models.Model):

    class Meta:
        verbose_name = _("profile")
        verbose_name_plural = _("profiles")

    USER_TYPE_CHOICES = (
        ('basic', _('Basic')),
        ('advanced', _('Advanced')),
    )

    cooperative_center = models.ForeignKey("CooperativeCenter", verbose_name=_("Cooperative Center"), null=True, blank=True, on_delete=models.PROTECT)
    user = models.OneToOneField(User, verbose_name="user", primary_key=True, on_delete=models.PROTECT)  # allow extension of default django User
    type = models.CharField(_("type"), max_length=30, choices=USER_TYPE_CHOICES, default="basic")

    def get_role_services(self):
        services = {}
        for item in UserRoleService.objects.filter(user=self.user):
            try:
                services[item.role_service.service].append(item.role_service.role)
            except KeyError:
                services[item.role_service.service] = [item.role_service.role]
        return services

    def is_basic(self):
        if self.type == "basic":
            return True
        return False

    def is_advanced(self):
        if self.type == "advanced":
            return True
        return False

# creates automatically and profile
def create_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile(user=instance)
        profile.save()

post_save.connect(create_profile, sender=User, dispatch_uid="user_create_profile")

class Role(Generic):

    class Meta:
        verbose_name = _("role")
        verbose_name_plural = _("roles")

    acronym = models.CharField(_('acronym'), max_length=55)
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_("description"), null=True, blank=True)

    def __str__(self):
        return str(self.name)

class RoleLocal(models.Model):

    class Meta:
        verbose_name = _("role translation")
        verbose_name_plural = _("role translations")

    role = models.ForeignKey(Role, verbose_name=_("role"), on_delete=models.CASCADE)
    language = models.CharField(_("language"), max_length=10, choices=LANGUAGES_CHOICES[1:])
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_("description"), null=True, blank=True)

    def __str__(self):
        return str(self.description)

class Service(Generic):

    class Meta:
        verbose_name = _("service")
        verbose_name_plural = _("services")

    acronym = models.CharField(_('acronym'), max_length=55)
    name = models.CharField(_('name'), max_length=255)
    roles = models.ManyToManyField("Role", through='RoleService')

    def __str__(self):
        return str(self.acronym)

class ServiceLocal(models.Model):

    class Meta:
        verbose_name = _("service translation")
        verbose_name_plural = _("service translations")

    service = models.ForeignKey(Service, verbose_name=_("service"), on_delete=models.CASCADE)
    language = models.CharField(_("language"), max_length=10, choices=LANGUAGES_CHOICES[1:])
    name = models.CharField(_('name'), max_length=255)


class RoleService(models.Model):

    role = models.ForeignKey(Role, on_delete=models.PROTECT)
    service = models.ForeignKey(Service, on_delete=models.PROTECT)

    def __str__(self):
        return str("%s | %s" % (self.role, self.service))


class UserRoleService(models.Model):

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    role_service = models.ForeignKey(RoleService, on_delete=models.CASCADE)


class CooperativeCenter(Generic):

    class Meta:
        verbose_name = _("cooperative center")
        verbose_name_plural = _("cooperative centers")

    code = models.CharField(_("code"), max_length=55, unique=True)
    country = models.ForeignKey(Country, verbose_name=_("country"), on_delete=models.PROTECT)
    institution = models.TextField(_("institution"), blank=True, null=True)

    def __str__(self):
        return str(self.code)

class Topic(Generic):

    class Meta:
        verbose_name = _("topic")
        verbose_name_plural = _("topics")

    name = models.CharField(_("name"), max_length=255)

    def __str__(self):
        return str(self.name)

class TopicLocal(models.Model):

    class Meta:
        verbose_name = _("topic translation")
        verbose_name_plural = _("topic translations")

    topic = models.ForeignKey(Topic, verbose_name=_("topic"), on_delete=models.CASCADE)
    language = models.CharField(_("language"), max_length=10, choices=LANGUAGES_CHOICES[1:])


class Network(Generic):

    class Meta:
        verbose_name = _("network")
        verbose_name_plural = _("networks")

    NETWORK_TYPE_CHOICES = (
        ('national', _('National')),
        ('thematic', _('Thematic')),
        ('institutional', _('Institutional')),
    )

    acronym = models.CharField(_('acronym'), max_length=255)
    responsible = models.ForeignKey(CooperativeCenter, verbose_name=_("Responsible Cooperative Center"), related_name="+", on_delete=models.PROTECT)
    topic = models.ForeignKey(Topic, verbose_name=_("topic"), blank=True, null=True, on_delete=models.PROTECT)
    type = models.CharField(_("type"), max_length=30, choices=NETWORK_TYPE_CHOICES, blank=True)
    country = models.ForeignKey(Country, verbose_name=_("country"), blank=True, null=True, on_delete=models.PROTECT)
    members = models.ManyToManyField(CooperativeCenter, through='NetworkMembership')

    def __str__(self):
        return str(self.acronym)

    def list_members(self):
        return [item.code for item in self.members.all()]


class NetworkMembership(models.Model):

    class Meta:
        verbose_name = _("Network Membership")
        verbose_name_plural = _("Network Memberships")

    network = models.ForeignKey(Network, on_delete=models.PROTECT)
    cooperative_center = models.ForeignKey(CooperativeCenter, verbose_name=_("Cooperative Center"), on_delete=models.PROTECT)

app/main/forms.py
#! coding: utf-8
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from main.models import *
from django import forms

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'is_active')

    type = forms.ChoiceField(label=_("Type"), choices=Profile.USER_TYPE_CHOICES)

    def __init__(self, *args, **kw):
        self.request = kw.pop("request")
        super(UserForm, self).__init__(*args, **kw)
        # reordering - keyOrder is deprecated, using fields order
        field_order = ['username', 'email', 'type', 'is_active']

        if hasattr(self.instance, 'profile'):
            self.fields['type'].initial = self.instance.profile.type

        # allow superuser to edit center code profile field
        if self.request.user.is_superuser:
            selected_cc = None
            if hasattr(self.instance, 'profile'):
                selected_cc = self.instance.profile.cooperative_center

            self.fields['cc'] = forms.ModelChoiceField( queryset=CooperativeCenter.objects.order_by('code'),
                empty_label=None, initial=selected_cc, label=_("Cooperative Center") )
            field_order.append('cc')
        else:
            # tk39 - allow advanced user to select cooperative center of users in their network (manage by his center)

            ccs_networks_responsible = []
            # check networks that request user CC manages
            networks_managed = Network.objects.filter(responsible=self.request.user.profile.cooperative_center)

            # create list with all CCs that user can view users
            for net_managed in networks_managed:
                ccs_networks_responsible.extend( [member.pk for member in net_managed.members.all()] )

            # only show select when request user CC manages a network
            if len(ccs_networks_responsible) > 1:
                selected_cc = self.instance.profile.cooperative_center if self.instance.id else None
                self.fields['cc'] = forms.ModelChoiceField(
                        queryset=CooperativeCenter.objects.filter(pk__in=ccs_networks_responsible).order_by('code'),
                        empty_label=None, initial=selected_cc, label=_("Cooperative Center") )
                field_order.append('cc')

        # Set field order using order_fields method
        self.order_fields(field_order)

    def save(self, commit=True, *args, **kw):
        super(UserForm, self).save(commit=True, *args, **kw)

        if self.request.user.is_superuser and not hasattr(self.instance, 'profile'):
            profile = Profile(user=self.request.user)
            profile.save()

        self.instance.profile.type = self.cleaned_data.get('type')
        if 'cc' in self.cleaned_data:
            self.instance.profile.cooperative_center = self.cleaned_data.get('cc')

        self.instance.profile.save()

        return self.instance

class NetworkForm(forms.ModelForm):

    class Meta:
        model = Network
        fields = ('country', 'topic', 'acronym', 'responsible', 'type')

    def __init__(self, *args, **kw):
        super(NetworkForm, self).__init__(*args, **kw)
        # order cc codes
        self.fields['responsible'] = forms.ModelChoiceField(queryset=CooperativeCenter.objects.order_by('code'),
                                                            label=_("Responsible Cooperative Center") )

class ServiceForm(forms.ModelForm):

    class Meta:
        model = Service
        fields = ( 'name', 'acronym')



class RoleForm(forms.ModelForm):

    class Meta:
        model = Role
        fields = ( 'name', 'acronym', 'description')

app/templates/main/edit-network.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Users" %} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li><a href="{% url 'main:networks' %}">{% trans "Networks" %}</a> <span class="divider">/</span></li>
    {% if is_new %}<li>{% trans "New Network" %}</li>
    {% else %}<li>{% trans "Edit Network" %}</li>{% endif %}
{% endblock %}

{% block extrajs %}
<script>
    $(function(){

        // adding permalinks to tabs
        var hash = window.location.hash,
        hashPart=hash.split('!')[1],
        activeTab=$('ul.nav a[href="#' + hashPart + '"]');
        activeTab && activeTab.tab('show');

        $('.nav-tabs a').click(function (e) {
            $(this).tab('show');
            window.location.hash = '#!'+$(this).attr('href').split('#')[1];
        });

        // search field
        search_field = $("#ccs_s");
        search_field.live('input', function(){
            $.ajax({
                url: "{% url 'api:get_ccs' %}",
                data: {code: search_field.val(), country: $("#ccs_country").val(), network: "{{ network.id }}"},
                success: function(data){
                    $("#ccs_content").empty();
                    $("#ccs_content").html(data);
                }
            });
        });

        // ajax that check and uncheck roles in users
        $(".checkbox_member").live('click', function(){
            var cc = $(this).attr('data-id');
            var checked = false;
            if($(this).is(':checked')) {
                var checked = true;
            }

            $.ajax({
                type: "GET",
                url: "{% url 'api:change_network_member' %}",
                data: {checked: checked, cc: cc, network: "{{ network.id }}"}
            }).done(function(result) {
                if(result === "0") {
                    alert("{% trans 'Error' %}");
                }
            });
        });
    });
</script>
{% endblock %}

{% block content %}
<div class='header'>
    <h2><i class='icon-sitemap'></i> {% trans "Edit Network" %}</h2>
</div>

<div class='body'>

    {% if not is_new %}
    <ul class="nav nav-tabs" id='tab'>
        <li class="active"><a href="#tab-data" data-toggle="tab">{% trans "Data" %}</a></li>
        <li><a href="#tab-centers" data-toggle="tab">{% trans "Included Centers" %}</a></li>
    </ul>
    {% endif %}

    <div class="tab-content">
        <div id="tab-data" class="tab-pane active">
            <form method="POST">{% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {{ field.label_tag }}
                        {{ field.errors }}
                        {{ field }}
                    {% endfor %}
                </fieldset>

                <div class="control-panel form-submit">
                    <button class="btn btn-primary btn-large">{% trans "Submit" %}</button>
                </div>
            </form>
        </div>

        {% if not is_new %}
        <div id='tab-centers' class="tab-pane">
            <input type="hidden" id="ccs_country" value="{{ cc_country }}">
            <div class='body'>
                <div class='pull-right'>
                    <div class="input-append">
                        <input type='text' name="s" id="ccs_s" placeholder="Type your center">
                        <button class="btn" type="button"><i class='icon-search'></i></button>
                    </div>
                </div>

                <table class='table'>
                    <thead>
                        <th></th>
                        <th>{% trans "Code" %}</th>
                        <th>{% trans "Institution" %}</th>
                    </thead>
                    <tbody id="ccs_content">
                        {% for cc in ccs %}
                        <tr>
                            <td><input type='checkbox' class="checkbox_member" data-id="{{ cc.id }}" {% if cc.id in members %}checked="true"{% endif %}></td>
                            <td>{{ cc.code }}</td>
                            <td><span title="{{ cc.institution }}">{{ cc.institution|truncatechars:"80" }}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% load i18n %}

{% block "title" %}{% trans "Dashboard" %} | {{ block.super }}{% endblock %}

{% block content %}    
    
    <!-- block alert -->
    {% if request.GET.message and request.GET.type %}
        <div class="alert alert-{{ request.GET.type }}">
            <button class="close" data-dismiss="alert">×</button>
            <strong>{% trans "Success!" %}</strong><br>
            {{ request.GET.message }}
        </div>
    {% endif %}
        
    <!--  header -->
    <div class='header'>
        <h2><i class='icon-home'></i> Dashboard <small>{{ user.username }} ({{ user.get_profile.cooperative_center }})</small></h2>
    </div>    
{% endblock %}

app/templates/main/networks.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Networks" %} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li>{% trans "Networks" %}</li>
{% endblock %}

{% block content %}
<form name="actions">
    <input type="hidden" name="orderby" value="{{ actions.orderby }}">
    <input type="hidden" name="order" value="{{ actions.order }}">
    <input type="hidden" name="page" value="{{ actions.page }}">
    <input type='hidden' name="s"  value="{{ actions.s }}">
</form>

<!--  header -->
<div class='header'>
    <h2><i class='icon-sitemap'></i> {% trans "Networks" %}</h2>

    {% if user.is_superuser %}
        <div class='pull-right'>
            <a href="{% url 'main:new_network' %}" class='btn btn-primary'><i class='icon-file'></i> {% trans "New Network" %}</a>
        </div>
    {% endif %}
</div>

<div class='body'>
    {% if actions.s %}
        <div>
            {% trans "Search" %}: <strong>{{ actions.s }}</strong>
            <a href="{% url 'main:networks' %}">[{% trans "clear" %}]</a>
        </div>
    {% endif %}

    <div class='pull-right'>
        <div class="input-append">
            <form name="search" onSubmit="return search();">
                <input type='text' name="s"  value="{{ actions.s }}" placeholder="{% trans "Search" %}">
                <button class="btn" type="submit"><i class='icon-search'></i></button>
            </form>
        </div>
    </div>

    <table class='table'>
        <thead>
            <th><a href="javascript:orderby('id');" id="id_id">#</a></th>
            <th><a href="javascript:orderby('acronym');" id="id_acronym">{% trans "Name" %}</a></th>
            <th><a href="javascript:orderby('responsible');" id="id_responsible">{% trans "Center Coordinator" %}</a></th>
            <th>{% trans "Actions" %}</th>
        </thead>
        <tbody>
            {% for network in networks %}
                <tr>
                    <td><a href="{% url 'main:edit_network' network.id %}">{{ network.id }}</a></td>
                    <td>{{ network.acronym }}</td>
                    <td>{{ network.responsible }}</td>
                    <td>
                        <a href="{% url 'main:edit_network' network.id %}" class='btn btn-mini'><i class='icon-pencil'></i></a>
                        <a href="#" class='btn btn-mini' title="{% trans 'Remove' %}"><i class='icon-remove'></i></a>
                    </td>

                </tr>
            {% endfor %}

        </tbody>
    </table>

</div>

{% endblock %}

app/templates/main/roles.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Users" %} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li>{% trans "Roles" %}</li>
{% endblock %}

{% block content %}
<form name="actions">
    <input type="hidden" name="orderby" value="{{ actions.orderby }}">
    <input type="hidden" name="order" value="{{ actions.order }}">
    <input type="hidden" name="page" value="{{ actions.page }}">
    <input type='hidden' name="s"  value="{{ actions.s }}">
</form>

<!--  header -->
<div class='header'>
    <h2><i class='icon-lock'></i> {% trans "Roles" %}</h2>

    <div class='pull-right'>
        <a href="{% url 'main:new_role' %}" class='btn btn-primary'><i class='icon-file'></i> {% trans "New Role" %}</a>
    </div>
</div>

<div class='body'>
    {% if actions.s %}
        <div>
            {% trans "Search" %}: <strong>{{ actions.s }}</strong>
            <a href="{% url 'main:roles' %}">[{% trans "clear" %}]</a>
        </div>
    {% endif %}

    <div class='pull-right'>
        <div class="input-append">
            <form name="search" onSubmit="return search();">
                <input type='text' name="s"  value="{{ actions.s }}" placeholder="{% trans "Search" %}">
                <button class="btn" type="submit"><i class='icon-search'></i></button>
            </form>
        </div>
    </div>

    <table class='table'>
        <thead>
            <th><a href="javascript:orderby('id');" id="id_id">#</a></th>
            <th><a href="javascript:orderby('name');" id="id_name">{% trans "Name" %}</a></th>
            <th><a href="javascript:orderby('acronym');" id="id_acronym">{% trans "Acronym" %}</a></th>
            <th>{% trans "Actions" %}</th>
        </thead>
        <tbody>
            {% for role in roles %}
                <tr>
                    <td><a href="{% url 'main:edit_role' role.id %}">{{ role.id }}</a></td>
                    <td>{{ role.name }}</td>
                    <td>{{ role.acronym }}</td>
                    <td><a href="{% url 'main:edit_role' role.id %}" class='btn btn-mini'><i class='icon-pencil'></i></a></td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

</div>

{% endblock %}

app/templates/main/services.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Services" %} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li>{% trans "Services" %}</li>
{% endblock %}

{% block content %}
<form name="actions">
    <input type="hidden" name="orderby" value="{{ actions.orderby }}">
    <input type="hidden" name="order" value="{{ actions.order }}">
    <input type="hidden" name="page" value="{{ actions.page }}">
    <input type='hidden' name="s"  value="{{ actions.s }}">
</form>

<!--  header -->
<div class='header'>
    <h2><i class='icon-star'></i> {% trans "Services" %}</h2>

    <div class='pull-right'>
        <a href="{% url 'main:new_service' %}" class='btn btn-primary'><i class='icon-file'></i> {% trans "New Service" %}</a>
    </div>
</div>

<div class='body'>
    {% if actions.s %}
        <div>
            {% trans "Search" %}: <strong>{{ actions.s }}</strong>
            <a href="{% url 'main:services' %}">[{% trans "clear" %}]</a>
        </div>
    {% endif %}

    <div class='pull-right'>
        <div class="input-append">
            <form name="search" onSubmit="return search();">
                <input type='text' name="s"  value="{{ actions.s }}" placeholder="{% trans "Search" %}">
                <button class="btn" type="submit"><i class='icon-search'></i></button>
            </form>
        </div>
    </div>

    <table class='table'>
        <thead>
            <th><a href="javascript:orderby('id');" id="id_id">#</a></th>
            <th><a href="javascript:orderby('name');" id="id_name">{% trans "Name" %}</a></th>
            <th><a href="javascript:orderby('acronym');" id="id_acronym">{% trans "Acronym" %}</a></th>
            <th>{% trans "Actions" %}</th>
        </thead>
        <tbody>
            {% for service in services %}
                <tr>
                    <td><a href="{% url 'main:edit_service' service.id %}">{{ service.id }}</a></td>
                    <td>{{ service.name }}</td>
                    <td>{{ service.acronym }}</td>
                    <td><a href="{% url 'main:edit_service' service.id %}" class='btn btn-mini'><i class='icon-pencil'></i></a></td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

</div>

{% endblock %}

app/templates/main/users.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Users" %} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li>{% trans "Users" %}</li>
{% endblock %}

{% block content %}

<form name="actions">
    <input type="hidden" name="orderby" value="{{ actions.orderby }}">
    <input type="hidden" name="order" value="{{ actions.order }}">
    <input type="hidden" name="page" value="{{ actions.page }}">
    <input type='hidden' name="s"  value="{{ actions.s }}">
    <input type='hidden' name="cc" value="{{ actions.cc }}">
</form>

<!--  header -->
<div class='header'>
    <h2><i class='icon-group'></i> {% trans "Users" %}</h2>

    <div class='pull-right'>
        <a href="{% url 'main:new_user' %}" class='btn btn-primary' title="{% trans "New User" %}"><i class='icon-file'></i> {% trans "New User" %}</a>
    </div>
</div>

<div class='body'>
    {% if actions.s %}
        <div>
            {% trans "Search" %}: <strong>{{ actions.s }}</strong>
            <a href="{% url 'main:users' %}">[{% trans "clear" %}]</a>
        </div>
    {% endif %}

    <div class='pull-right'>
        <div class="input-append">
            <form name="search" onSubmit="return search();">
                {% if cooperative_centers|length > 1 %}
                    <select name="cc">
                        <option value="">{% trans "Cooperative Center" %}</option>
                        {% for center in cooperative_centers %}
                            <option value="{{ center.pk }}" {% if actions.cc == center.pk|stringformat:"s" %}selected{% endif %}>{{ center.code }}</option>
                        {% endfor %}
                    </select>
                    &nbsp;
                    &nbsp;
                {% endif %}
                <input type='text' name="s"  value="{{ actions.s }}" placeholder="{% trans "username or e-mail" %}">
                <button class="btn" type="submit"><i class='icon-search'></i></button>
            </form>
        </div>
    </div>

    <table class='table'>
        <thead>
            <th><a href="javascript:orderby('id');" id="id_id">#</a></th>
            <th><a href="javascript:orderby('username');" id="id_username">{% trans "Name" %}</a></th>
            <th><a href="javascript:orderby('email');" id="id_email">{% trans "Email" %}</a></th>
            <th><a href="javascript:orderby('services');" id="id_email">{% trans "Services" %}</a></th>
            <th><a href="javascript:orderby('is_active');" id="id_is_active">{% trans "Active?" %}</a></th>
            {% if user.is_superuser or show_users_cc %}
                <th>{% trans "Cooperative Center" %}</th>
            {% endif %}
            <th>{% trans "Actions" %}</th>
        </thead>
        <tbody>
            {% for appuser in users %}
                <tr>
                    <td>{{ appuser.id }}</td>
                    <td>{{ appuser }}</td>
                    <td>{{ appuser.email }}</td>
                    <td>{% for service, roles in appuser.profile.get_role_services.items %}

                        <span title="{% for role in roles %}{{ role }}{% if not forloop.last %}, {% endif %}{% endfor %}">{{ service }}</span>
                        {% if not forloop.last %} | {% endif %}
                    {% endfor %}</td>
                    <td>{% if appuser.is_active %}<i class='icon-ok'></i>{% else %}<i class='icon-minus-sign'></i>{% endif %}</td>

                    {% if user.is_superuser or show_users_cc %}
                        <td><span title="{{ appuser.profile.cooperative_center.institution }}">{{ appuser.profile.cooperative_center.code }}</span></th>
                    {% endif %}

                    <td><a href="{% url 'main:edit_user' appuser.id %}" class='btn btn-mini' title="{% trans 'Edit' %}"><i class='icon-pencil'></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination pull-right">
        <ul>
        {% if users.has_previous %}
            <li>
                <a href="?page={{ users.previous_page_number }}&s={{ actions.s }}&orderby={{ actions.orderby }}&order={{ actions.order }}?&cc={{ actions.cc }}" class="">Anterior</a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="">Anterior</a>
            </li>
        {% endif %}

        {% for page in pages %}
        <li {% if page == users.number %}class="active"{% endif %}>
            <a href="?page={{ page }}&s={{ actions.s }}&orderby={{ actions.orderby }}&order={{ actions.order }}?&cc={{ actions.cc }}">{{ page }}</a>
        </li>
        {% endfor %}

        {% if users.has_next %}
            <li>
                <a href="?page={{ users.next_page_number }}&s={{ actions.s }}&orderby={{ actions.orderby }}&order={{ actions.order }}?&cc={{ actions.cc }}">Próxima</a>
            </li>
        {% else %}
            <li class="disabled">
                <a href="">Próxima</a>
            </li>
        {% endif %}
        </ul>
    </div>
</div>
{% endblock %}